config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'recipes#index'
  
  resources :bookmarks
  resources :shopping_lists
  resources :ingredient_list_items
  resources :users
  resources :recipes

  get '/imports', to: 'imports#new'
  post '/imports', to: 'imports#create'
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    has_one :recipe
    has_one :user
end

app/models/import.rb
class Import
    # Table-less model https://stackoverflow.com/a/33143196
    include ActiveModel::Model
    
    attr_accessor :file
    
    validates :file, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    # Ingredients are only used in the ingredient list. But the ingredient list has
    # multiple applications. One is showing ingredients in a recipe; another is a shopping list.
    
    # Usually in Rails you would connect them so that there is a relationship in their
    # models.
    
    # I think a better idea would be to programmatically match ingredients.
    # For instance if you have 3 recipes and one calls for 2 "onions" and another calls for 1 "onion" and another for 1/2 cup "ONION"
    # The system should be smart enough to convert all of those to "Onion" type and to at least
    # Add up measurements which are of the same type. So that would become 3 Onion and 1/2 Cup Onion on the shopping list.
    
    # None of that requires that I have a table for Ingredients. But for now I'm going to keep this table just in case I want it later.
end

app/models/ingredient_list.rb
class IngredientList < ApplicationRecord
    has_and_belongs_to_many :recipes
    
    validates :checked, presence: true
    validates :quantity, presence: true
    validates :ingredient_id, presence: true
end

app/models/ingredient_list_item.rb
class IngredientListItem < ApplicationRecord
    validates :ingredient, presence: true
    validates :quantity, presence: true
    
    before_save :make_checked_not_nil
    def make_checked_not_nil
        if self.checked == nil
            self.checked = false
        end
    end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredient_list_items
    accepts_nested_attributes_for :ingredient_list_items
    has_one :user # Recipe owner
    
    validates :name, presence: true, length: {minimum: 3}
    validates :short_description, presence: true, length: {minimum: 3}
    validates :instructions, presence: true
    validates :license_status, acceptance: true
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
    has_many :ingredient_list_items
    has_many :recipes
end

app/models/user.rb
class User < ApplicationRecord
    has_many :bookmarks
    has_many :shopping_lists
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    if @bookmark.save
      redirect_to @bookmark
    else
      render :new
    end
  end
  
  def edit
    @bookmark = Bookmark.find(params[:id])
  end
  
  def update
    @bookmark = Bookmark.find(params[:id])
    
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark
    else
      render :edit
    end
  end

  private
    def bookmark_params
      params.require(:bookmark).permit()
    end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def new
      @import = Import.new
  end

  def create
    f = params[:import][:file]
    File.foreach(f.path).with_index do |line, index|
        splitLine = line.split(',') #handle csv files
        splitLine.each do |entry|
            entry.tr!("\r\n", "")
            entry.titleize!
            next if entry.length < 1
            next if not Ingredient.where(name: entry).empty?
            ingredient = Ingredient.new(name: entry)
            ingredient.save
        end
    end
    redirect_to "/ingredients"
  end
end

app/controllers/ingredient_list_items_controller.rb
class IngredientListItemsController < ApplicationController
  def index
    @ingredient_list_items = IngredientListItem.all
  end

  def show
    @ingredient_list_item = IngredientListItem.find(params[:id])
  end

  def new
    @ingredient_list_item = IngredientListItem.new
  end

  def create
    @ingredient_list_item = IngredientListItem.new(ingredient_list_item_params)

    if @ingredient_list_item.save
      redirect_to @ingredient_list_item
    else
      render :new
    end
  end
  
  def edit
    @ingredient_list_item = IngredientListItem.find(params[:id])
  end
  
  def update
    @ingredient_list_item = IngredientListItem.find(params[:id])
    
    if @ingredient_list_item.update(ingredient_list_item_params)
      redirect_to @ingredient_list_item
    else
      render :edit
    end
  end

  private
    def ingredient_list_item_params
      params.require(:ingredient_list_item).permit(:checked, :quantity, :unit, :ingredient, :recipe_id)
    end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
    def index
        @recipes = Recipe.all
    end
    
    def show
        @recipe = Recipe.find(params[:id])
    end
    
    def show_image
        send_data @recipe.image, :disposition => 'inline'
    end
    
    def new
        @recipe = Recipe.new
    end
    
    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to @recipe
        else
            render :new
        end
    end
    
    def edit
        @recipe = Recipe.find(params[:id])
    end
    
    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            redirect_to @recipe
        else
            render :edit
        end
    end
    
    private
        def recipe_params
            params.require(:recipe).permit(:name, :image, :short_description, :ingredient, 
            :instructions, :long_description, :license_status)
        end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @recipes = Recipe.all
    end
    
    def show
        @recipe = Recipe.find(params[:id])
    end
    
    def show_image
        send_data @recipe.image, :disposition => 'inline'
    end
    
    def new
        @recipe = Recipe.new
        @recipe.ingredient_list_items.build
    end
    
    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.ingredient_list_items.each do |item|
            item.checked = false if item.checked == nil
        end
        begin
            @recipe.save!
            redirect_to @recipe
        rescue Exception => e
            puts e.message
            puts e.backtrace.inspect
            render :new
        end
    end
    
    def edit
        @recipe = Recipe.find(params[:id])
        if @recipe.ingredient_list_items == nil || @recipe.ingredient_list_items.length < 1
            # This should only happen if 'new' was not called when the object was first built.    
            @recipe.ingredient_list_items.build
        end
    end
    
    def update
        @recipe = Recipe.find(params[:id])
        # TODO can I get an easier to work with object out of this map like how 
        # .update must be getting the object from the params?
        begin
            @recipe.update!(recipe_params)
            redirect_to @recipe
        rescue Exception => e
            puts e.message
            puts e.backtrace.inspect
            render :edit
        end
    end
    
    private
        def recipe_params
            params.require(:recipe).permit(:name, :image, :short_description, 
            :instructions, :long_description, :license_status, 
            ingredient_list_items_attributes: [:id, :quantity, :checked, :unit, :ingredient])
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/ingredient_list_items_helper.rb
module IngredientListItemsHelper
end

app/helpers/ingredient_lists_helper.rb
module IngredientListItemsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredient_list_items/_form.html.erb
<!-- 1. make this a partial view for "Search"
2. Set @search_results
3. Iterate over each search result and display it in the partial. -->

<%= form_with model: ingredient_list_item do |form| %>
  <div class="form-check">
    <%= form.check_box :checked, class: 'form-check-input' %>
    <%= form.label :checked, class: 'form-check-label' %>
  </div>
  
  <div class="mb-3">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, step: :any, class: 'form-control' %>
    <% ingredient_list_item.errors.full_messages_for(:quantity).each do |message| %>
        <div class="local-invalid-feedback">
          <%= message %>
        </div>
    <% end %>
  </div>
  
  <div class="mb-3">
    <%= form.label :unit %>
    <%= form.select :unit, ['', 'teaspoon', 'Tablespoon', 'fluid ounce', 'cup', 'pint', 'quart', 'gallon', 'ounce', 'pound', 'ml', 'liter'], {}, class: 'form-select' %>
    <% ingredient_list_item.errors.full_messages_for(:unit).each do |message| %>
        <div class="local-invalid-feedback">
          <%= message %>
        </div>
    <% end %>
  </div>
  
  <div class="mb-3">
    <%= form.label :ingredient %>
    <%= form.text_field :ingredient, class: 'form-control' %>
    <% ingredient_list_item.errors.full_messages_for(:ingredient).each do |message| %>
      <divclass="local-invalid-feedback">
        <%= message %>
      </div>
    <% end %>
  </div>
  
  <div class="mb-3">
    <%= form.label :recipe_id, "Recipe ID" %>
    <%= form.number_field :recipe_id, class: 'form-control' %>
    <% ingredient_list_item.errors.full_messages_for(:recipe_id).each do |message| %>
        <div class="local-invalid-feedback">
          <%= message %>
        </div>
    <% end %>
  </div>

  <div>
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/ingredient_list_items/edit.html.erb
<h1>Edit Ingredient List Item</h1>

<%= render "form", ingredient_list_item: @ingredient_list_item %>

app/views/ingredient_list_items/index.html.erb
<h1>Ingredient List Items</h1>
<%= link_to 'New Ingredient List', new_ingredient_list_item_path, class: "btn btn-primary", role: "button" %>

<ul>
    <% @ingredient_list_items.each do |ingredient_list_item| %>
    <li>
        <% if ingredient_list_item.ingredient != nil && ingredient_list_item.recipe_id != nil %>
        <%= link_to "#{ingredient_list_item.quantity} #{ingredient_list_item.ingredient} is part of the recipe with ID #{ingredient_list_item.recipe_id}", ingredient_list_item %>
        <% elsif ingredient_list_item.ingredient != nil %>
        <%= link_to "#{ingredient_list_item.quantity} #{ingredient_list_item.ingredient}", ingredient_list_item %>
        <% else %>
        <%= link_to ingredient_list_item.id, ingredient_list_item %> (ingredient name not set; ID is shown)
        <% end %>
    </li>
    <% end %>
</ul>

app/views/ingredient_list_items/new.html.erb
<h1>New Ingredient List Item</h1>

<%= render "form", ingredient_list_item: @ingredient_list_item %>

app/views/ingredient_list_items/show.html.erb
<h1>Ingredient List Item</h1>
<p><%= "Checked; " if @ingredient_list_item.checked %></p>
<p><%= @ingredient_list_item.quantity %> <%= @ingredient_list_item.unit %> <%= @ingredient_list_item.ingredient %></p>
<p>Recipe ID: <%= @ingredient_list_item.recipe_id %></p>

<%= link_to 'Edit', edit_ingredient_list_item_path(@ingredient_list_item), class: "btn btn-primary", role: "button" %>