config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'recipes#index'
  
  resources :bookmarks
  resources :shopping_lists
  resources :ingredient_list_items
  resources :users
  resources :recipes

  get '/imports', to: 'imports#new'
  post '/imports', to: 'imports#create'
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    has_one :recipe
    has_one :user
end

app/models/import.rb
class Import
    # Table-less model https://stackoverflow.com/a/33143196
    include ActiveModel::Model
    
    attr_accessor :file
    
    validates :file, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    # Ingredients are only used in the ingredient list. But the ingredient list has
    # multiple applications. One is showing ingredients in a recipe; another is a shopping list.
    
    # Usually in Rails you would connect them so that there is a relationship in their
    # models.
    
    # I think a better idea would be to programmatically match ingredients.
    # For instance if you have 3 recipes and one calls for 2 "onions" and another calls for 1 "onion" and another for 1/2 cup "ONION"
    # The system should be smart enough to convert all of those to "Onion" type and to at least
    # Add up measurements which are of the same type. So that would become 3 Onion and 1/2 Cup Onion on the shopping list.
    
    # None of that requires that I have a table for Ingredients. But for now I'm going to keep this table just in case I want it later.
end

app/models/ingredient_list.rb
class IngredientList < ApplicationRecord
    has_and_belongs_to_many :recipes
    
    validates :checked, presence: true
    validates :quantity, presence: true
    validates :ingredient_id, presence: true
end

app/models/ingredient_list_item.rb
class IngredientListItem < ApplicationRecord
    validates :ingredient, presence: true
    validates :quantity, presence: true
    
    before_save :make_checked_not_nil
    def make_checked_not_nil
        if self.checked == nil
            self.checked = false
        end
    end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredient_list_items
    accepts_nested_attributes_for :ingredient_list_items
    has_one :user # Recipe owner
    
    validates :name, presence: true, length: {minimum: 3}
    validates :short_description, presence: true, length: {minimum: 3}
    validates :instructions, presence: true
    validates :license_status, acceptance: true
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
    has_many :ingredient_list_items
    has_many :recipes
end

app/models/user.rb
class User < ApplicationRecord
    has_many :bookmarks
    has_many :shopping_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    if @bookmark.save
      redirect_to @bookmark
    else
      render :new
    end
  end
  
  def edit
    @bookmark = Bookmark.find(params[:id])
  end
  
  def update
    @bookmark = Bookmark.find(params[:id])
    
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark
    else
      render :edit
    end
  end

  private
    def bookmark_params
      params.require(:bookmark).permit()
    end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def new
      @import = Import.new
  end

  def create
    f = params[:import][:file]
    File.foreach(f.path).with_index do |line, index|
        splitLine = line.split(',') #handle csv files
        splitLine.each do |entry|
            entry.tr!("\r\n", "")
            entry.titleize!
            next if entry.length < 1
            next if not Ingredient.where(name: entry).empty?
            ingredient = Ingredient.new(name: entry)
            ingredient.save
        end
    end
    redirect_to "/ingredients"
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to @ingredient
    else
      render :new
    end
  end
  
  def edit
    @ingredient = Ingredient.find(params[:id])
  end
  
  def update
    @ingredient = Ingredient.find(params[:id])
    
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient
    else
      render :edit
    end
  end
  
  private
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
    def index
        @recipes = Recipe.all
    end
    
    def show
        @recipe = Recipe.find(params[:id])
    end
    
    def show_image
        send_data @recipe.image, :disposition => 'inline'
    end
    
    def new
        @recipe = Recipe.new
    end
    
    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to @recipe
        else
            render :new
        end
    end
    
    def edit
        @recipe = Recipe.find(params[:id])
    end
    
    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            redirect_to @recipe
        else
            render :edit
        end
    end
    
    private
        def recipe_params
            params.require(:recipe).permit(:name, :image, :short_description, :ingredient, 
            :instructions, :long_description, :license_status)
        end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @recipes = Recipe.all
    end
    
    def show
        @recipe = Recipe.find(params[:id])
    end
    
    def show_image
        send_data @recipe.image, :disposition => 'inline'
    end
    
    def new
        @recipe = Recipe.new
        @recipe.ingredient_list_items.build
    end
    
    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.ingredient_list_items.each do |item|
            item.checked = false if item.checked == nil
        end
        begin
            @recipe.save!
            redirect_to @recipe
        rescue Exception => e
            puts e.message
            puts e.backtrace.inspect
            render :new
        end
    end
    
    def edit
        @recipe = Recipe.find(params[:id])
        if @recipe.ingredient_list_items == nil || @recipe.ingredient_list_items.length < 1
            # This should only happen if 'new' was not called when the object was first built.    
            @recipe.ingredient_list_items.build
        end
    end
    
    def update
        @recipe = Recipe.find(params[:id])
        # TODO can I get an easier to work with object out of this map like how 
        # .update must be getting the object from the params?
        begin
            @recipe.update!(recipe_params)
            redirect_to @recipe
        rescue Exception => e
            puts e.message
            puts e.backtrace.inspect
            render :edit
        end
    end
    
    private
        def recipe_params
            params.require(:recipe).permit(:name, :image, :short_description, 
            :instructions, :long_description, :license_status, 
            ingredient_list_items_attributes: [:id, :quantity, :checked, :unit, :ingredient])
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/ingredient_list_items_helper.rb
module IngredientListItemsHelper
end

app/helpers/ingredient_lists_helper.rb
module IngredientListItemsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipe/_form.html.erb
<% # I tried to use path_recipe but it resolves to /recipes/ which is wrong. %>
<%= form_with scope: :recipe, url: recipe_path(@recipe) do |form| %>
<div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
    <% recipe.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
    <% end %>
</div>
<div class="mb-3">
    <%= form.label :image %>
    <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg', class: 'form-control-file' %>
</div>
<div class="mb-3">
    <%= form.label :short_description %>
    <%= form.text_area :short_description, class: 'form-control' %>
    <% recipe.errors.full_messages_for(:short_description).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
    <% end %>
</div>
<div class="mb-3">
    <%= form.label :ingredient %>
    <%= form.text_area :ingredient, class: 'form-control' %>
    <% recipe.errors.full_messages_for(:ingredient).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
    <% end %>
</div>
<div class="mb-3">
    <%= form.label :instructions %>
    <%= form.text_area :instructions, class: 'form-control', rows: 6 %>
    <% recipe.errors.full_messages_for(:instructions).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
    <% end %>
</div>
<div class="mb-3">
    <%= form.label :long_description %>
    <%= form.text_area :long_description, class: 'form-control', rows: 6 %>
</div>
<div class="form-check">
    <%= form.check_box :license_status, class: 'form-check-input' %>
    <!--input type="checkbox" class="form-check-input" id="check1"-->
    <label class="form-check-label" for="check1">I attest that this recipe is of my own creation or is in the public domain. Furthermore, I release this work under the <a href="https://creativecommons.org/licenses/by/4.0/legalcode">Creative Commons - Attribution 4.0 License</a> (<a href="https://creativecommons.org/licenses/by/4.0/">license summary</a>).</label>
</div>

<%= form.submit class: 'btn btn-primary' %>

<% end %>

app/views/recipe/new.html.erb
<h1><%= @recipe.name %></h1>
<% if @recipe.image %>
<img src=""/>
<% end %>
<p><%= @recipe.short_description %></p>
<h3>Ingredients</h3>
<p><%= @recipe.ingredient %></p>
<h3>Instructions</h3>
<p><%= @recipe.instructions %></p>
<% if @recipe.long_description && @recipe.long_description.length > 0 %>
<h3>About This Recipe</h3>
<p><%= @recipe.long_description %></p>
<% end %>

app/views/recipe/show.html.erb
<h1><%= @recipe.name %></h1>
<% if @recipe.image %>
<%= image_tag url_for(:recipe => "recipe", :action => "show_image") %>
<% end %>
<p><%= @recipe.short_description %></p>
<h3>Ingredients</h3>
<p><%= @recipe.ingredient %></p>
<h3>Instructions</h3>
<p><%= @recipe.instructions %></p>
<% if @recipe.long_description && @recipe.long_description.length > 0 %>
<h3>About This Recipe</h3>
<p><%= @recipe.long_description %></p>
<% end %>

<%= link_to 'Edit this Recipe', edit_recipe_path(@recipe), class: "btn btn-primary", role: "button" %>

app/views/recipes/_form.html.erb
<%= form_with model: recipe do |form| %>
<div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
    <% recipe.errors.full_messages_for(:name).each do |message| %>
        <div class="local-invalid-feedback">
          <%= message %>
        </div>
    <% end %>
</div>
<div class="input-group mb-3">
    <%= form.label "Cover Photo", class: 'input-group-text' %>
    <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg', class: 'form-control' %>
</div>

<div class="mb-3">
    <%= form.label :short_description %>
    <%= form.text_area :short_description, class: 'form-control' %>
    <% recipe.errors.full_messages_for(:short_description).each do |message| %>
        <div class="local-invalid-feedback">
          <%= message %>
        </div>
    <% end %>
</div>

<label>Ingredients</label>
<div class="container">
    <%= form.fields_for :ingredient_list_items do |list_items_form| %>
    <!-- may have to set form_for instead of form_with above when using this -->
        
    <!-- TODO fix validation for .errors for this nested form -->
      <div class="mb-3">
        <%= list_items_form.label :quantity %>
        <%= list_items_form.number_field :quantity, step: :any, class: 'form-control' %>
        <% recipe.errors.full_messages_for(:quantity).each do |message| %>
            <div class="local-invalid-feedback">
              <%= message %>
            </div>
        <% end %>
      </div>
        
      <div class="mb-3">
        <%= list_items_form.label :unit %>
        <%= list_items_form.select :unit, ['', 'teaspoon', 'Tablespoon', 'fluid ounce', 'cup', 'pint', 'quart', 'gallon', 'ounce', 'pound', 'ml', 'liter'], {}, class: 'form-select' %>
        <% recipe.errors.full_messages_for(:unit).each do |message| %>
            <div class="local-invalid-feedback">
              <%= message %>
            </div>
        <% end %>
      </div>
        
      <div class="mb-3">
        <%= list_items_form.label :ingredient %>
        <%= list_items_form.text_field :ingredient, class: 'form-control' %>
        <% recipe.errors.full_messages_for(:ingredient).each do |message| %>
          <divclass="local-invalid-feedback">
            <%= message %>
          </div>
        <% end %>
      </div>
    <% end %>
</div>

<div class="mb-3">
    <%= form.label :instructions %>
    <%= form.text_area :instructions, class: 'form-control', rows: 6 %>
    <% recipe.errors.full_messages_for(:instructions).each do |message| %>
        <div class="local-invalid-feedback">
          <%= message %>
        </div>
    <% end %>
</div>
<div class="mb-3">
    <%= form.label :long_description %>
    <%= form.text_area :long_description, class: 'form-control', rows: 6 %>
    <% recipe.errors.full_messages_for(:long_description).each do |message| %>
        <div class="local-invalid-feedback"><%= message %></div>
    <% end %>
</div>
<div class="form-check">
    <% if recipe.errors.full_messages_for(:license_status) == nil || recipe.errors.full_messages_for(:license_status).length < 1 %>
    <%= form.check_box :license_status, class: "form-check-input" %>
    <% else %>
    <%= form.check_box :license_status, class: "form-check-input is-invalid" %>
    <% end %>
    <label class="form-check-label" for="check1">I attest that this recipe is of my own creation or is in the public domain. Furthermore, I release this work under the <a href="https://creativecommons.org/licenses/by/4.0/legalcode">Creative Commons - Attribution 4.0 License</a> (<a href="https://creativecommons.org/licenses/by/4.0/">license summary</a>).</label>
    <% recipe.errors.full_messages_for(:license_status).each do |message| %>
        <div class="local-invalid-feedback"><%= message %></div>
    <% end %>
</div>

<%= form.submit class: 'btn btn-primary' %>

<% end %>

app/views/recipes/edit.html.erb
<h1>Edit a Recipe</h1>
<p>Thank you for contributing! :)</p>
<%= render "form", recipe: @recipe %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>
<%= link_to 'Add a Recipe', new_recipe_path, class: "btn btn-primary", role: "button" %>
<% @recipes.each do |recipe| %>
    <div class="card">
        <a href="<%= recipe_path(recipe) %>" style="all:unset;color:unset;cursor:pointer;">
        <% if recipe.image %>
        <img class="card-img-top" src="">
        <%end%>
        <div class="card-body">
            <h5 class="card-title"><%= recipe.name %></h5>
            <p class="card-text"><%= recipe.short_description %></p>
        </div>
        </a>
    </div>
<% end %>

app/views/recipes/new.html.erb
<h1>Add a Recipe</h1>
<p>Thank you for contributing! :)</p>
<%= render "form", recipe: @recipe %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<% if @recipe.image %>
<%= image_tag url_for(:recipe => "recipe", :action => "show_image") %>
<% end %>
<p><%= @recipe.short_description %></p>
<h3>Ingredients</h3>
<% @recipe.ingredient_list_items.each do |ingredient_list_item| %>
    <p><%= ingredient_list_item.quantity %> <%= ingredient_list_item.unit %> <%= ingredient_list_item.ingredient %></p>
<% end %>
<h3>Instructions</h3>
<p><%= @recipe.instructions %></p>
<% if @recipe.long_description && @recipe.long_description.length > 0 %>
<h3>About This Recipe</h3>
<p><%= @recipe.long_description %></p>
<% end %>

<%= link_to 'Edit this Recipe', edit_recipe_path(@recipe), class: "btn btn-primary", role: "button" %>